USE [master]
GO

/****** Object:  Database [TitmeTable]    Script Date: 23.11.2022 20:53:20 ******/
CREATE DATABASE [TitmeTable]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TitmeTable', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TitmeTable.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TitmeTable_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TitmeTable_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TitmeTable].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TitmeTable] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TitmeTable] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TitmeTable] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TitmeTable] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TitmeTable] SET ARITHABORT OFF 
GO

ALTER DATABASE [TitmeTable] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TitmeTable] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TitmeTable] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TitmeTable] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TitmeTable] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TitmeTable] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TitmeTable] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TitmeTable] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TitmeTable] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TitmeTable] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TitmeTable] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TitmeTable] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TitmeTable] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TitmeTable] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TitmeTable] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TitmeTable] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TitmeTable] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TitmeTable] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TitmeTable] SET  MULTI_USER 
GO

ALTER DATABASE [TitmeTable] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TitmeTable] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TitmeTable] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TitmeTable] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TitmeTable] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TitmeTable] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TitmeTable] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TitmeTable] SET  READ_WRITE 
GO

